#include ui
#include console/console
#include contextMenu
#include utils/magiclines
#include searchdataGenerator
#include cardFactory
#include WebRequest
#include sleeves
#include playerData

function onLoad()
    buildUI()
end

function onPlayerAction(player, action, targets)
    handleContextMenu(player, action, targets)
end

function onChat(message, player)
    if tryExecuteCommand(message, player) then return false end
end
