COMMAND_PATTERN = "^%$(%w+)%s?(.*)"
COMMAND = { }

#include commands

function tryExecuteCommand(message, player)
    _, _, command, params = message:find(COMMAND_PATTERN)
    if command ~= nil then
        if COMMAND[command] ~= nil then
            COMMAND[command](params, player)
        else
            print(command.." is not a command")
        end
        return true
    end
end

-- add new commands like this:
-- COMMAND.name = function(parameters, player)
--     // code here
-- end
